"""report_builder.py - Human-readable report generation for the serah_demo package.

No network access, no brokerage connection, no order-placement capability.
"""
from __future__ import annotations
from typing import List
from .models import EvidencePacket

SAFETY_DISCLAIMER = "SYNTHETIC DATA ONLY. Not a trade recommendation. No order capability."

def build_review_packet_text(packet: EvidencePacket) -> str:
      lines = [
                f"# Review Packet - {packet.ticker} - {packet.timestamp_utc[:10]}",
                f"> **{SAFETY_DISCLAIMER}**",
                "",
                f"**Packet ID:** {packet.packet_id}",
                f"**Ticker:** {packet.ticker}",
                f"**Status:** {packet.status}",
                f"**Tier:** {packet.tier} - {packet.tier_reason}",
                "",
                f"**Price:** ${packet.price:.2f} | **Prev Close:** ${packet.prev_close:.2f} | **Move:** {packet.move_pct:+.2f}%",
                "",
                f"**Move math check:** ({packet.price:.2f} - {packet.prev_close:.2f}) / {packet.prev_close:.2f} * 100 = {(packet.price-packet.prev_close)/packet.prev_close*100:.2f}% " + ("[OK]" if abs((packet.price-packet.prev_close)/packet.prev_close*100 - packet.move_pct) < 0.5 else "[MISMATCH]"),
                "",
                f"**Bid:** ${packet.spread.bid:.2f} | **Ask:** ${packet.spread.ask:.2f} | **Spread:** {packet.spread.spread_pct:.2f}%",
                f"**Spread check:** ask >= bid: {'[OK]' if packet.spread.ask >= packet.spread.bid else '[FAIL]'}",
                "",
                f"**Catalyst:** {'Present' if packet.catalyst.present else 'Absent'} | Type: {packet.catalyst.type or 'N/A'} | Freshness: {packet.catalyst.freshness}",
                "",
                f"**RVOL:** {packet.volume.rvol_current:.2f}x" if packet.volume.rvol_current else "**RVOL:** N/A",
                "",
                f"**Ready for audit:** {'Yes' if packet.is_ready_for_audit else 'No'}",
                f"**Content hash:** {packet.content_hash[:48]}",
                "",
                f"*{SAFETY_DISCLAIMER}*",
      ]
      return "\n".join(lines)

def build_operator_report(packets: List[EvidencePacket], invalid_count: int = 0, invalid_errors=None) -> str:
      lines = [
                "OPERATOR SESSION REPORT",
                "=======================",
                "Generated by: serah_demo v1.0 (SYNTHETIC DEMO ONLY)",
                f"Packets valid: {len(packets)}",
                f"Packets failed: {invalid_count}",
                "",
      ]
      for i, p in enumerate(packets, 1):
                lines += [f"  [{i}] {p.ticker} Tier:{p.tier} Move:{p.move_pct:+.2f}% Ready:{'Y' if p.is_ready_for_audit else 'N'}"]
            lines += [
                      "",
                      "SAFETY SUMMARY",
                      "  No network requests",
                      "  No brokerage API",
                      "  No orders placed",
                      "  All data synthetic",
                      "END OF REPORT",
            ]
    return "\n".join(lines)
