"""report_builder.py - Human-readable report generation for the serah_demo package.

No network access, no brokerage connection, no order-placement capability.
"""

from __future__ import annotations

from typing import List

from .models import EvidencePacket

SAFETY_DISCLAIMER = "SYNTHETIC DATA ONLY. Not a trade recommendation. No order capability."


def build_review_packet_text(packet: EvidencePacket) -> str:
    """Build a human-readable markdown review packet from an EvidencePacket."""
    out = []
    out.append(f"# Review Packet - {packet.ticker} - {packet.timestamp_utc[:10]}")
    out.append(f"> **{SAFETY_DISCLAIMER}**")
    out.append("")
    out.append(f"**Packet ID:** {packet.packet_id}")
    out.append(f"**Ticker:** {packet.ticker}")
    out.append(f"**Status:** {packet.status}")
    out.append(f"**Tier:** {packet.tier} - {packet.tier_reason}")
    out.append("")
    out.append(f"**Price:** ${packet.price:.2f} | **Prev Close:** ${packet.prev_close:.2f} | **Move:** {packet.move_pct:+.2f}%")
    out.append("")
    pct = (packet.price - packet.prev_close) / packet.prev_close * 100
    out.append(f"**Move math check:** expected {pct:.2f}% - recorded {packet.move_pct:.2f}%")
    out.append("")
    ok = '[OK]' if packet.spread.ask >= packet.spread.bid else '[FAIL]'
    out.append(f"**Bid:** ${packet.spread.bid:.2f} | **Ask:** ${packet.spread.ask:.2f} | **Spread:** {packet.spread.spread_pct:.2f}%")
    out.append(f"**Spread check:** ask >= bid: {ok}")
    out.append("")
    cat_present = 'Present' if packet.catalyst.present else 'Absent'
    out.append(f"**Catalyst:** {cat_present} | Type: {packet.catalyst.type or 'N/A'} | Freshness: {packet.catalyst.freshness}")
    out.append("")
    if packet.volume.rvol_current is not None:
        out.append(f"**RVOL:** {packet.volume.rvol_current:.2f}x")
    else:
        out.append("**RVOL:** N/A")
    out.append("")
    ready = 'Yes' if packet.is_ready_for_audit else 'No'
    out.append(f"**Review-Ready (human review):** {ready}")
    out.append(f"**Content hash:** {packet.content_hash[:48]}")
    out.append("")
    out.append(f"*{SAFETY_DISCLAIMER}*")
    return "\n".join(out)


def build_operator_report(
    packets: List[EvidencePacket],
    invalid_count: int = 0,
    invalid_errors=None,
) -> str:
    """Build a compact operator session summary."""
    out = [
        "OPERATOR SESSION REPORT",
        "=======================",
        "Generated by: serah_demo v1.0 (SYNTHETIC DEMO ONLY)",
        f"Packets valid: {len(packets)}",
        f"Packets failed: {invalid_count}",
        "",
    ]
    for i, p in enumerate(packets, 1):
        ready = 'Y' if p.is_ready_for_audit else 'N'
        out.append(f"  [{i}] {p.ticker} Tier:{p.tier} Move:{p.move_pct:+.2f}% Review-Ready:{ready}")
    out += [
        "",
        "SAFETY SUMMARY",
        "  No network requests",
        "  No brokerage API",
        "  No orders placed",
        "  All data synthetic",
        f"  {SAFETY_DISCLAIMER}",
    ]
    if invalid_errors:
        out.append(f"  First rejection reason: {invalid_errors[0]}")
    return "\n".join(out)
